# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["nvme" "xhci_pci" "ahci" "thunderbolt" "usbhid" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-amd" "r8125"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/f650059f-d101-4999-9135-2625e30ad1a4";
    fsType = "btrfs";
    options = ["subvol=root" "compress-force=zstd:3" "space_cache=v2" "discard=async"];
  };

  fileSystems."/.swapvol" = {
    device = "/dev/disk/by-uuid/f650059f-d101-4999-9135-2625e30ad1a4";
    fsType = "btrfs";
    options = ["subvol=swap"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/4089-2D71";
    fsType = "vfat";
    options = ["fmask=0022" "dmask=0022"];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/9b7f156b-764e-49d8-874d-7966497a6b22";
    fsType = "btrfs";
    options = ["subvol=home" "compress-force=zstd:3" "space_cache=v2" "discard=async"];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/f650059f-d101-4999-9135-2625e30ad1a4";
    fsType = "btrfs";
    options = ["subvol=nix" "compress-force=zstd:3" "space_cache=v2" "discard=async"];
  };

  fileSystems."/var/log" = {
    device = "/dev/disk/by-uuid/f650059f-d101-4999-9135-2625e30ad1a4";
    fsType = "btrfs";
    options = ["subvol=log" "compress-force=zstd:3" "space_cache=v2" "discard=async"];
  };

  swapDevices = [];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp118s0u2.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  hardware.enableRedistributableFirmware = true;
}
